"""create tables

Revision ID: 54ab3f8dad77
Revises: 
Create Date: 2025-12-25 12:00:18.114760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ab3f8dad77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('store_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_street', sa.String(), nullable=False),
    sa.Column('address_city', sa.String(), nullable=False),
    sa.Column('address_state', sa.String(length=2), nullable=False),
    sa.Column('address_postal_code', sa.String(length=5), nullable=False),
    sa.Column('address_country', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('store_services',
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_name'], ['services.name'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('store_id', 'service_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_services')
    op.drop_table('stores')
    op.drop_table('services')
    # ### end Alembic commands ###
