"""add phone hours to stores

Revision ID: a79bbda027ea
Revises: 54ab3f8dad77
Create Date: 2025-12-26 11:58:34.199468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79bbda027ea'
down_revision: Union[str, Sequence[str], None] = '54ab3f8dad77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'hours')
    op.drop_column('stores', 'phone')
    # ### end Alembic commands ###
